# Generated by Django 5.0.1 on 2024-01-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('class_level', models.IntegerField()),
                ('subjects', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('father_first_name', models.CharField(max_length=100)),
                ('father_last_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
            ],
        ),
    ]
